### ISSUE TITLE
[help] How to compile CS344 in Ubuntu?

### ISSUE THREAD

**Issue by tiendung** [gwenzek/cudaz#1]
Thank you for providing us a way to program GPU using Zig. I try to compilte CS344 in Ubuntu but got following error. Look like it cannot find `nvidia-ptxjitcompiler`. What is it and how can I get it? Thank you :)

```
cudaz/CS344$ zig build
error: ld.lld: unable to find library -lcuda
error: ld.lld: unable to find library -lnvidia-ptxjitcompiler
error: hw1...
error: The following command exited with error code 1:
/home/t/repos/zig/build/stage3/bin/zig build-exe /home/t/repos/.save/cudaz/CS344/src/hw1.zig -lc -needed-lcuda -needed-lnvidia-ptxjitcompiler -cflags -DLODEPNG_COMPILE_ERROR_TEXT -- /home/t/repos/.save/cudaz/CS344/lodepng/lodepng.c --cache-dir /home/t/repos/.save/cudaz/CS344/zig-cache --global-cache-dir /home/t/.cache/zig --name hw1 --pkg-begin cudaz /home/t/repos/.save/cudaz/CS344/cudaz/src/cuda.zig --pkg-begin cudaz_options /home/t/repos/.save/cudaz/CS344/zig-cache/options/Q3gflWFB41wSGI-78tI7r_a7FAK9JJ_LYgtalrTnc6nZmCHrXifyAk-7wXS2I96n --pkg-end --pkg-end -I /home/t/repos/.save/cudaz/CS344/cudaz/src -I /usr/local/cuda/include -I /home/t/repos/.save/cudaz/CS344/src -I /home/t/repos/.save/cudaz/CS344/lodepng -L /usr/local/cuda/lib64 --enable-cache
error: the following build command failed with exit code 1:
/home/t/repos/.save/cudaz/CS344/zig-cache/o/4a4e2b6f6f25d0514921a24713b15618/build /home/t/repos/zig/build/stage3/bin/zig /home/t/repos/.save/cudaz/CS344 /home/t/repos/.save/cudaz/CS344/zig-cache /home/t/.cache/zig
```

**Comment by gwenzek** [comment]
Congrats on being the first user! 
Where is Cuda installed on your system?
You should have directory with all the libcuda.so

The path is currently hardcoded here: https://github.com/gwenzek/cudaz/blob/68638782c52035c572af61db346082732ffb7014/CS344/build.zig#L3

You should change it to the value on your system.

**Comment by tiendung** [comment]
Nice, I follow your guideline at https://github.com/gwenzek/cudaz/blob/main/cudaz/sdk.zig#L141 and it solved.

**Comment by tiendung** [comment]
Now I run into another problem:

```
~/repos/cudaz/CS344$ ./zig-out/bin/hw1 
info: ***** HW1 ******
info: Loaded Image (rgb24)557x313: (...[30]u8@234ede8...)
warning(Cuda): Loading Cuda module from local file /home/t/repos/cudaz/CS344/zig-out/bin/hw1.ptx
error(Cuda): CUDA_ERROR_UNSUPPORTED_PTX_VERSION(222): the provided PTX was compiled with an unsupported toolchain.
thread 24513 panic: Something looks wrong with compiled device code
cudaz/src/cuda_errors.zig:102:12: 0x2899d1 in silent_check (hw1)
        => @panic("Something looks wrong with compiled device code"),
           ^
cudaz/src/cuda_errors.zig:53:24: 0x2800a4 in check (hw1)
    return silent_check(result);
                       ^
cudaz/src/cuda.zig:453:49: 0x28387a in defaultModule (hw1)
        check(cu.cuModuleLoad(&_default_module, @ptrCast([*c]const u8, file))) catch |err| {
                                                ^
cudaz/src/cuda.zig:489:64: 0x2836e9 in init (hw1)
            var code = cu.cuModuleGetFunction(&f, defaultModule(), @ptrCast([*c]const u8, name));
                                                               ^
src/hw1.zig:38:66: 0x28598b in main (hw1)
    const kernel = try cudaz.CudaKernel("rgba_to_greyscale").init();
                                                                 ^
/home/t/repos/zig/build/stage3/lib/zig/std/start.zig:614:37: 0x286d97 in main (hw1)
            const result = root.main() catch |err| {
                                    ^
Aborted
```

**Comment by gwenzek** [comment]
What's your nvcc version? In SDK.zig I'm targetting a recent PTX version and maybe you have an older toolchain that can't compile it. Note you can manually edit the ptx files and compile them with 'nvcc' to see what version your Cuda version supports.

You can either upgrade your compiler or downgrade the ptx version in https://github.com/gwenzek/cudaz/blob/68638782c52035c572af61db346082732ffb7014/cudaz/sdk.zig#L87

You can also lookup Dev branch

**Comment by tiendung** [comment]
Thank for pointing out. After switching to `dev` branch I can run `hw5`, (the others still having unsupported ptx error).

Is below normal behavior of `hw5`?

```
/repos/cudaz/CS344$ ./zig-out/bin/hw5 
warning(Cuda): Loading Cuda module from local file /home/t/repos/cudaz/CS344/zig-out/bin/hw5_kernel.zig.ptx
info(hw5): ***** HW5 ******
info(hw5): atomicHistogram of 10240000 array took 4.471e+00ms
info(hw5): atomicHistogram bandwith: 9.162e+03MB/s
index 119 incorrect. expected 1, found 0
info(hw5): bychunkHistogram of 10240000 array took 4.454e+00ms
info(hw5): bychunkHistogram bandwith: 9.195e+03MB/s
info(hw5): fastHistogram of 10240000 array took 0.000e+00ms
info(hw5): fastHistogram bandwith: infMB/s
```

**Comment by gwenzek** [comment]
So historically I wrote hw{1..4} using C kernels and `nvcc` you can still run those with `zig build run_nvcc`.
They seems to work, except I have a bug in `nvcc/hw2.zig` which leads to a truncated image (probably X,Y confusion).

Then I wrote hw5 fully in Zig. This one used to work but seems to compute invalid results now with last Zig and LLVM. The LLVM backend that compiles to PTX has changed in the meantime and some possible sloppy code now get's compiled into something wrong I need to investigate.

Then I rewrote hw{1,2,3} kernels in Zig. hw1 works, hw2 produces an totally incorrect image, and hw3 is not finished and currently panics due to an out of bound memory access.
So I have some more work to do here.

For you I'd focus on making `zig build hw1` working, this is the simplest kernel and it produces correct results. (It's was commented in the dev branch, I'm pushing a commit to re-enable it)
Maybe start with `zig build run_nvcc` so we can understand if you're CUDA toolchain works as expected.

If you want more help, I'll need at least the output of:

```
which nvcc
nvcc --version
nvidia-smi
zig env
```

Do you have `.ptx` appearing in `zig-out/bin` ? can you compile them with `ptxas` ? (this tool should be in you cuda installation dir next to nvcc)

**Comment by gwenzek** [comment]
> Nice, I follow your guideline at https://github.com/gwenzek/cudaz/blob/main/cudaz/sdk.zig#L141 and it solved.

I should probably print this to the console on failure, but not sure how to do this.

**Comment by tiendung** [comment]
Thank you. I'm trying with different cuda toolkit version. We let you know when I'm done.

**Comment by tiendung** [comment]
After reinstall Nvidia driver to make it match with latest cuda-12, I can run both hw* and hw*_nvcc. Thanks for you help 💯
